name: $(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: 'JJ Microsoft Azure Internal Consumption (82fb79bf-ee69-4a57-a76c-26153e544afe)'
  
stages:
- stage: 'Deploy'
  displayName: 'Deploy'
  jobs:
  - job: 'CLI'
    steps:
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: $(subscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az account show

  - job: 'DeployVnet'
    displayName: 'Deploy virtual network'    
    steps:
    - script: chmod +x vnet/*.sh
    - script: ./deploy.sh
      displayName: 'Vnet deploy'
      workingDirectory: vnet
  - job: 'DeployFw'
    displayName: 'Deploy firewall'    
    dependsOn: 'DeployVnet'
    steps:
    - script: chmod +x fw/*.sh
    - script: ./deploy.sh
      displayName: 'Fw deploy'
      workingDirectory: fw      
  - job: 'DeployAppGw'
    displayName: 'Deploy application gateway'
    dependsOn: 'DeployVnet'
    steps:
    - script: chmod +x appgw/*.sh
    - script: ./deploy.sh
      displayName: 'AppGw deploy'
      workingDirectory: appgw   