name: $(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Prepare'
  displayName: 'Prepare'
  jobs:
  - job: 'Fix'
    displayName: 'Fix scripts'
    steps:
    - script: chmod +x vnet/*.sh
    - script: chmod +x fw/*.sh
    - script: chmod +x appgw/*.sh
    - script: chmod +x appgw/*.sh    

- stage: 'Deploy'
  displayName: 'Deploy'
  jobs:
  - job: 'PlanDeploy'
    displayName: 'Plan and Deploy'
    steps:
    - script: ./deploy.sh
      displayName: 'Vnet deploy'
      workingDirectory: vnet