apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:                                  # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: aksname
      type: Opaque
      data:
        - objectName: aksname                     # name of the mounted content to sync. this could be the object name or object alias. The mount is mandatory for the content to be synced as Kubernetes secret.
          key: aksname
  parameters:
    usePodIdentity: "false"                       # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 7992a2ab-cd9b-4c6f-ac03-7242c02ab26a  # [OPTIONAL] if not provided, will default to the identity ID of the VM
    keyvaultName: jjakskv                         # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: aksname
          objectType: secret                      # object types: secret, key or cert
          objectAlias: aksname
          objectVersion:                          # [OPTIONAL] object versions, default to latest if empty
    tenantId: "5bf07991-ef59-43e0-861c-ab35a6cfc932"                               # the tenant ID of the KeyVault